### ISSUE TITLE
Strange arrangement of VictoryPie etc 'invalid prop transform of type string supplied to Path'

### ISSUE THREAD

**Issue by MarcelBlockchain** [FormidableLabs/victory-native#234]
Hi there,
just found out about victory-native, really awesome! Wanted to get started and got a strange arrangement of VictoryPie. 'alignItems' and 'justifyContent' did not help.

![screen shot 2018-01-07 at 11 49 05](https://user-images.githubusercontent.com/26665436/34650018-dc9c8ed4-f3a0-11e7-99e5-1851fba57a0e.png)

Failed prop type: Invalid prop `transform` of type `string` supplied to `Path`, expected `object`

![screen shot 2018-01-07 at 11 41 17](https://user-images.githubusercontent.com/26665436/34650005-9cff6d00-f3a0-11e7-98a8-f66469d498b7.png)

Victory- Area, Line, Bar etc all work perfectly though.
Opened a new Expo Project and copied and pasted the example code from: https://github.com/expo/examples/tree/master/with-victory-native

Problem also appears in a basic environment like below. With and without containerComponent :
```
render() {
    return (
      <VictoryPie
        data={[
          { x: "Ethereum", y: 34 },
          { x: "Bitcoin", y: 30 },
          { x: "Dash", y: 20}
        ]}
      />
    );
  }
```

Has something to do with:

```
import React from "react";
import { Path } from "react-native-svg";
import { Slice } from "victory-core/es";
import { NativeHelpers } from "../../index";

export default class extends Slice {
  // Overrides method in victory-core
  renderSlice(path, style, events) {
    const { role, shapeRendering, className, origin } = this.props;
    const nativeStyle = NativeHelpers.getStyle(style);
    const transform = origin ? `translate(${origin.x} ${origin.y})` : undefined;
    return (
      <Path
        className={className}
        role={role || "presentation"}
        shapeRendering={shapeRendering || "auto"}
        d={path}
        transform={transform}
        {...nativeStyle}
        {...events}
      />
    );
  }
}
```

```

  "dependencies": {
    "expo": "^24.0.0",
    "lodash": "^4.17.4",
    "react": "16.0.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-24.0.0.tar.gz",
    "react-navigation": "^1.0.0-beta.22",
    "victory-native": "^0.16.6"
  }

```
I thought I'd find the solution at the [React-Native Transforms Docs](https://facebook.github.io/react-native/docs/transforms.html#transform), but even disabling Animation did not help.
Thanks for helping!

**Comment by robertobrogi** [comment]
Hi, have you find a solution?
I tried this link https://github.com/expo/examples/tree/master/with-victory-native and the pie work perfect...
is chenge the victory version?

**Comment by robertobrogi** [comment]
with "victory-native": "^0.15.0" work all perfect :)

**Comment by MarcelBlockchain** [comment]
It's true! "^0.15.0" works. Thanks!

**Comment by matt-leonardo** [comment]
Me too, I use 0.15.   In addition, I need downgraded react-native-svg to version earlier.  Otherwise the graph causes the app to crash.

**Comment by reubenab** [comment]
I would love to be able to use `cornerRadius` for my `VictoryBar` alongside my VictoryPie but that's only available in 0.16.1, so would love if this were fixed!

**Comment by lucasapereira** [comment]
Same problem

**Comment by boygirl** [comment]
Latest versions: `victory-native@0.17.0`, `react-native-svg@^6.1.0`

I'm not able to reproduce this issue locally with the versions above.

**Comment by omars94** [comment]
I'm not sure why you closed this issue even thought you didn't give a clear explanation on how to fix it
I'm still getting the same error when trying to use victory pie
@boygirl how did you fix this issue?
I'm using this code 
      `<VictoryPie
width={400}
        center={true}
        height={400}
        data={[
          { x: 1, y: 2, label: "one" },
          { x: 2, y: 3, label: "two" },
          { x: 3, y: 5, label: "three" }
        ]}
        animate={{ duration: 1500 }}
        theme={VictoryTheme.material}
        responsive={true}
        style={{ labels: { fontSize: 20, fill: "white" } }}
      />`
and its producing it like this
![screenshot from 2018-09-13 11-11-45](https://user-images.githubusercontent.com/23584801/45476013-92020600-b746-11e8-97c9-01d0d8f18f38.jpg)
and also showing this warning
![screenshot_2018-09-13-11-28-23](https://user-images.githubusercontent.com/23584801/45476691-44869880-b748-11e8-93dd-1b3ee08e6a0c.png)
